/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AgentPumpInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_PRICE"
      | "GRADUATION_MC"
      | "INITIAL_SUPPLY"
      | "PRECISION"
      | "RESERVE_RATIO"
      | "activateAgent"
      | "agentCount"
      | "agentList"
      | "agents"
      | "balances"
      | "buy"
      | "createToken"
      | "deactivateAgent"
      | "getAgentBalance"
      | "getAgentInfo"
      | "getAllAgents"
      | "getBuyPrice"
      | "getMarketCap"
      | "getPrice"
      | "getSellPrice"
      | "getToken"
      | "isAgent"
      | "owner"
      | "registerAgent"
      | "renounceOwnership"
      | "sell"
      | "tokenCount"
      | "tokens"
      | "transferOwnership"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentDeactivated"
      | "AgentRegistered"
      | "OwnershipTransferred"
      | "TokenCreated"
      | "TokenGraduated"
      | "Trade"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GRADUATION_MC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PRECISION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "RESERVE_RATIO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activateAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "balances",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createToken",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentBalance",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketCap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "BASE_PRICE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "GRADUATION_MC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PRECISION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "RESERVE_RATIO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agentCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agentList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSellPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AgentDeactivatedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [wallet: AddressLike, name: string, avatar: string];
  export type OutputTuple = [wallet: string, name: string, avatar: string];
  export interface OutputObject {
    wallet: string;
    name: string;
    avatar: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenCreatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    name: string,
    symbol: string,
    creator: AddressLike,
    metadata: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    name: string,
    symbol: string,
    creator: string,
    metadata: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    name: string;
    symbol: string;
    creator: string;
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenGraduatedEvent {
  export type InputTuple = [tokenId: BigNumberish, finalMC: BigNumberish];
  export type OutputTuple = [tokenId: bigint, finalMC: bigint];
  export interface OutputObject {
    tokenId: bigint;
    finalMC: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    agent: AddressLike,
    isBuy: boolean,
    amount: BigNumberish,
    price: BigNumberish,
    cost: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    agent: string,
    isBuy: boolean,
    amount: bigint,
    price: bigint,
    cost: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    agent: string;
    isBuy: boolean;
    amount: bigint;
    price: bigint;
    cost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentPump extends BaseContract {
  connect(runner?: ContractRunner | null): AgentPump;
  waitForDeployment(): Promise<this>;

  interface: AgentPumpInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_PRICE: TypedContractMethod<[], [bigint], "view">;

  GRADUATION_MC: TypedContractMethod<[], [bigint], "view">;

  INITIAL_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  PRECISION: TypedContractMethod<[], [bigint], "view">;

  RESERVE_RATIO: TypedContractMethod<[], [bigint], "view">;

  activateAgent: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  agentCount: TypedContractMethod<[], [bigint], "view">;

  agentList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, bigint, bigint, boolean] & {
        name: string;
        avatar: string;
        wallet: string;
        totalTrades: bigint;
        totalVolume: bigint;
        pnl: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  balances: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  buy: TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [void],
    "payable"
  >;

  createToken: TypedContractMethod<
    [name: string, symbol: string, metadata: string],
    [bigint],
    "nonpayable"
  >;

  deactivateAgent: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  getAgentBalance: TypedContractMethod<
    [tokenId: BigNumberish, agent: AddressLike],
    [bigint],
    "view"
  >;

  getAgentInfo: TypedContractMethod<
    [wallet: AddressLike],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        name: string;
        avatar: string;
        totalTrades: bigint;
        totalVolume: bigint;
        pnl: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getAllAgents: TypedContractMethod<[], [string[]], "view">;

  getBuyPrice: TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;

  getMarketCap: TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;

  getPrice: TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;

  getSellPrice: TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;

  getToken: TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        name: string;
        symbol: string;
        metadata: string;
        creator: string;
        createdAt: bigint;
        totalSupply: bigint;
        reserveBalance: bigint;
        price: bigint;
        marketCap: bigint;
        graduated: boolean;
      }
    ],
    "view"
  >;

  isAgent: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerAgent: TypedContractMethod<
    [wallet: AddressLike, name: string, avatar: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sell: TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokenCount: TypedContractMethod<[], [bigint], "view">;

  tokens: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, bigint, bigint, boolean] & {
        name: string;
        symbol: string;
        metadata: string;
        creator: string;
        createdAt: bigint;
        totalSupply: bigint;
        reserveBalance: bigint;
        graduated: boolean;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GRADUATION_MC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INITIAL_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RESERVE_RATIO"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activateAgent"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "agentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, bigint, bigint, boolean] & {
        name: string;
        avatar: string;
        wallet: string;
        totalTrades: bigint;
        totalVolume: bigint;
        pnl: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "balances"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createToken"
  ): TypedContractMethod<
    [name: string, symbol: string, metadata: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateAgent"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgentBalance"
  ): TypedContractMethod<
    [tokenId: BigNumberish, agent: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentInfo"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        name: string;
        avatar: string;
        totalTrades: bigint;
        totalVolume: bigint;
        pnl: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllAgents"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getBuyPrice"
  ): TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketCap"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSellPrice"
  ): TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getToken"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        name: string;
        symbol: string;
        metadata: string;
        creator: string;
        createdAt: bigint;
        totalSupply: bigint;
        reserveBalance: bigint;
        price: bigint;
        marketCap: bigint;
        graduated: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAgent"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [wallet: AddressLike, name: string, avatar: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sell"
  ): TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tokenCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokens"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, bigint, bigint, boolean] & {
        name: string;
        symbol: string;
        metadata: string;
        creator: string;
        createdAt: bigint;
        totalSupply: bigint;
        reserveBalance: bigint;
        graduated: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AgentDeactivated"
  ): TypedContractEvent<
    AgentDeactivatedEvent.InputTuple,
    AgentDeactivatedEvent.OutputTuple,
    AgentDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenCreated"
  ): TypedContractEvent<
    TokenCreatedEvent.InputTuple,
    TokenCreatedEvent.OutputTuple,
    TokenCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenGraduated"
  ): TypedContractEvent<
    TokenGraduatedEvent.InputTuple,
    TokenGraduatedEvent.OutputTuple,
    TokenGraduatedEvent.OutputObject
  >;
  getEvent(
    key: "Trade"
  ): TypedContractEvent<
    TradeEvent.InputTuple,
    TradeEvent.OutputTuple,
    TradeEvent.OutputObject
  >;

  filters: {
    "AgentDeactivated(address)": TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;
    AgentDeactivated: TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;

    "AgentRegistered(address,string,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokenCreated(uint256,string,string,address,string)": TypedContractEvent<
      TokenCreatedEvent.InputTuple,
      TokenCreatedEvent.OutputTuple,
      TokenCreatedEvent.OutputObject
    >;
    TokenCreated: TypedContractEvent<
      TokenCreatedEvent.InputTuple,
      TokenCreatedEvent.OutputTuple,
      TokenCreatedEvent.OutputObject
    >;

    "TokenGraduated(uint256,uint256)": TypedContractEvent<
      TokenGraduatedEvent.InputTuple,
      TokenGraduatedEvent.OutputTuple,
      TokenGraduatedEvent.OutputObject
    >;
    TokenGraduated: TypedContractEvent<
      TokenGraduatedEvent.InputTuple,
      TokenGraduatedEvent.OutputTuple,
      TokenGraduatedEvent.OutputObject
    >;

    "Trade(uint256,address,bool,uint256,uint256,uint256)": TypedContractEvent<
      TradeEvent.InputTuple,
      TradeEvent.OutputTuple,
      TradeEvent.OutputObject
    >;
    Trade: TypedContractEvent<
      TradeEvent.InputTuple,
      TradeEvent.OutputTuple,
      TradeEvent.OutputObject
    >;
  };
}
